### ISSUE TITLE
Modules on top of logos

### ISSUE THREAD

**Issue by NicoKarasch** [redcast/RedCast-OnTime#1]
It would be nice if it's possible to change the layer of the logos. So one could put the output of a module (e.g. web) on top of the station's logo(s) (to hide them).

**Comment by redcast** [comment]
This is not a issue. This is a request.

**Comment by Bohoaush** [comment]
> 
> 
> This is not a issue. This is a request.

Sorry if I'm not right I'm new to github, so my understanding of it is quite limited. But don't you have to create a new branche before it is possible to create requests?
