### ISSUE TITLE
Log browser window calendar display

### ISSUE THREAD

**Issue by noquierouser** [redcast/RedCast-OnTime#6]
The calendar to the left of the Log browser window isn't showing the sunday column. Resizing the window doesn't seem to fix the issue as well.

![Calendar without sunday column in Log Browser window](https://user-images.githubusercontent.com/463168/47043911-3a035880-d165-11e8-93a8-dfdc8e70f043.png)

**Comment by redcast** [comment]
Thank you. We will fix this on next Update.
